name: CI

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          version: 2026.7.18
      - run: mise exec -- task ci
